=== marsender/atoll-digital-library/dtd/atoll_plugin_xmlexec.dtd
<!--
	atoll_plugin_xmlexec.dtd
	// 09/08/08 Version 1.0 Start implementation
-->

<!ELEMENT atoll-plugin-xmlexec (ReqAll+|ResAll+)>
<!ATTLIST atoll-plugin-xmlexec version NMTOKEN #REQUIRED>

<!ELEMENT ReqAll (ReqCol|ReqDb|ReqInfo|ReqInit|ReqUtil|ReqDoc|ReqSearch|ReqIndex|ReqSearchCrit|ReqSearchScreen|ReqUsr)+>
<!ELEMENT ResAll (ResCol|ResDb|ResInfo|ResInit|ResUtil|ResDoc|ResSearch|ResIndex|ResSearchCrit|ResSearchScreen|ResUsr)+>

<!ELEMENT ReqInit (Col|DbHome|OutFile|User)+>
<!ELEMENT ResInit (Col|DbHome|OutFile|User)+>

<!ELEMENT ReqInfo (Col|DbHome|LogFile|TraceFile|OutFile|User|Version)+>
<!ELEMENT ResInfo (Col|DbHome|LogFile|TraceFile|OutFile|User|Version)+>

<!ELEMENT ReqDb (AddCol|DelCol|GetCol|GetListCol|SetCol)+>
<!ELEMENT ResDb (AddCol|DelCol|GetCol|ListCol|SetCol)*>

<!ELEMENT ReqCol (AddDoc|AddField|DelDoc|DelField|DelDocIndex|GetDoc|GetField|GetListDoc|GetListField|GetListNdx|IndexDoc|SetDoc|SetField)+>
<!ELEMENT ResCol (AddDoc|AddField|DelDoc|DelField|DelDocIndex|GetDoc|GetField|IndexDoc|ListDoc|ListField|ListNdx|ListField|SetDoc|SetField)*>

<!ELEMENT ReqUtil ((Tool|Stat|Binary|UserInfo),User?,Col?,Param*)>
<!ELEMENT ResUtil ((Tool|Stat|Binary|UserInfo),Param*,Result)>

<!ELEMENT ReqDoc (SearchId?,ToolBar?,((DocPagPos,Link?)|File|Tag),Search?)>
<!ELEMENT ResDoc (SearchId,Plage,ToolBar?,DocTexte*)>

<!ELEMENT ReqSearch (((SearchCrit,Corpus?)|(SearchId,Corpus?)|Corpus)?,NewSearch?,Export?,Contexte?,Def?,Plage,TypeRes?)>
<!ELEMENT ResSearch (SearchId,Corpus?,Export?,Contexte?,Def?,Plage, TypeRes,NbRes,Status?,DocTexte*)>

<!ELEMENT ReqIndex (IdCrit?,((SearchCrit,Corpus?)|(SearchId,Corpus?)|Corpus)?,IdCrit?,Export?,TypeIndex,TypeTri?,Plage,Grec?)>
<!ELEMENT ResIndex (SearchId,Export?,Grec?,Plage,Texte*)>

<!ELEMENT ReqSearchCrit ((SearchId|Tag))>
<!ELEMENT ResSearchCrit (SearchId,SearchCrit)>

<!ELEMENT ReqSearchScreen (User,Col)>
<!ELEMENT ResSearchScreen (SearchScreen*)>

<!ELEMENT ReqUsr (SearchId?,Plage?,DocTexte?,(Corpus,TypeRes?)?,(Title,SearchCrit*)?,DocPagPos*)>
<!ATTLIST ReqUsr UsrAction CDATA #IMPLIED>
<!ELEMENT ResUsr ((Plage|DocTexte|DocPagPos|Corpus|Title|SearchCrit)*)>
<!ATTLIST ResUsr UsrAction CDATA #IMPLIED>

<!ELEMENT LogFile (#PCDATA)>

<!ELEMENT TraceFile (#PCDATA)>

<!ELEMENT OutFile (#PCDATA)>

<!ELEMENT Action (Open|Close|ClearCacheCol|ClearCacheUsr|ClearCacheUsrDyn|ClearCacheUsrHst|ClearCacheUsrReq
  |StartIndex|UpdateIndex|GetStatus|MakeTabmat)+>
<!ELEMENT File (Tabmat?,(Name|DocPagPos),Plage)>
<!ELEMENT SetOfFiles (BinFile)+>
<!ELEMENT BinFile (Name,Base64)>
<!ELEMENT Plage ((DocPagPos|Min|Mot),Nb,Max?)>

<!ELEMENT ToolBar (Object)+>
<!ATTLIST ToolBar Mode CDATA #IMPLIED>

<!ELEMENT Object (Enabled,Checked,Texte)*>
<!ATTLIST Object Type CDATA #IMPLIED>

<!ELEMENT SearchCrit (Crit)+>

<!ELEMENT SearchScreen (OpeRech*,Crit+)>
<!ATTLIST SearchScreen Mode CDATA #IMPLIED>

<!ELEMENT Crit (IdCrit,Texte)>
<!ATTLIST Crit Type CDATA #IMPLIED>

<!ELEMENT TypeRes (Doc|Page|Pos)>

<!ELEMENT Pos (Para|Phrase|NbMot)>

<!ELEMENT TypeIndex (Index|Liste|Article)>

<!ELEMENT TypeTri (MotFreq|FreqCroi|FreqDecr|FinMot)>

<!ELEMENT Status (Open|Close|StartIndex|Texte)>

<!ELEMENT DocTexte (DocPagPos,Anno?,Signet?,Facsim?,Link?,Texte)>

<!ELEMENT NbRes (NbDoc,NbPage,NbPos)>

<!ELEMENT Name (#PCDATA)>

<!ELEMENT User (#PCDATA)>

<!ELEMENT SearchId (#PCDATA)>

<!ELEMENT Version (#PCDATA)>

<!ELEMENT Tool (#PCDATA)>

<!ELEMENT Stat (#PCDATA)>

<!ELEMENT Binary (#PCDATA)>

<!ELEMENT UserInfo (#PCDATA)>

<!ELEMENT Param (#PCDATA)>
<!ATTLIST Param Name CDATA #IMPLIED>

<!ELEMENT Corpus (#PCDATA)>
<!ATTLIST Corpus Num CDATA #IMPLIED>

<!ELEMENT Title (#PCDATA)>
<!ATTLIST Title Num CDATA #IMPLIED>

<!ELEMENT Result (#PCDATA)>

<!ELEMENT DocPagPos (#PCDATA)>

<!ELEMENT Tag (#PCDATA)>

<!ELEMENT Search (#PCDATA)>

<!ELEMENT Min (#PCDATA)>

<!ELEMENT Mot (#PCDATA)>

<!ELEMENT Nb (#PCDATA)>

<!ELEMENT Max (#PCDATA)>

<!ELEMENT IdCrit (#PCDATA)>

<!ELEMENT Texte (#PCDATA)>

<!ELEMENT Doc (#PCDATA)>

<!ELEMENT Page (#PCDATA)>

<!ELEMENT NbMot (#PCDATA)>

<!ELEMENT NbDoc (#PCDATA)>

<!ELEMENT NbPage (#PCDATA)>

<!ELEMENT NbPos (#PCDATA)>

<!ELEMENT OpeRech (#PCDATA)>

<!ELEMENT DbHome (#PCDATA)>

<!ELEMENT Open EMPTY>

<!ELEMENT Close EMPTY>

<!ELEMENT ClearCacheCol EMPTY>

<!ELEMENT ClearCacheUsr EMPTY>

<!ELEMENT ClearCacheUsrDyn EMPTY>

<!ELEMENT ClearCacheUsrHst EMPTY>

<!ELEMENT ClearCacheUsrReq EMPTY>

<!ELEMENT Col EMPTY>
<!ATTLIST Col
	ColId CDATA #IMPLIED
	ColName CDATA #IMPLIED
	ColTitle CDATA #IMPLIED
	ColSalt CDATA #IMPLIED
	>

<!ELEMENT AddCol (#PCDATA)>
<!ATTLIST AddCol
	ColId CDATA #IMPLIED
	ColName CDATA #IMPLIED
	ColTitle CDATA #IMPLIED
	ColSalt CDATA #IMPLIED
	>

<!ELEMENT SetCol (#PCDATA)>
<!ATTLIST SetCol
	ColId CDATA #IMPLIED
	ColName CDATA #IMPLIED
	ColTitle CDATA #IMPLIED
	ColSalt CDATA #IMPLIED
	>

<!ELEMENT GetCol EMPTY>
<!ATTLIST GetCol
	ColId CDATA #IMPLIED
	>

<!ELEMENT DelCol EMPTY>
<!ATTLIST DelCol
	ColId CDATA #REQUIRED
	>

<!ELEMENT AddDoc (#PCDATA)>
<!ATTLIST AddDoc
	DocNum CDATA #IMPLIED
	CountPge CDATA #IMPLIED
	FileName CDATA #IMPLIED
	DcMetadata CDATA #IMPLIED
	IndexerConfig CDATA #IMPLIED
	RecordBreakerConfig CDATA #IMPLIED
	Uuid CDATA #IMPLIED
	XsltCode CDATA #IMPLIED
	XmlValidation (0|1|yes|no|true|false) "false"
	IsIndexed (0|1|yes|no|true|false) "false"
	>

<!ELEMENT SetDoc (#PCDATA)>
<!ATTLIST SetDoc
	DocNum CDATA #IMPLIED
	CountPge CDATA #IMPLIED
	FileName CDATA #IMPLIED
	DcMetadata CDATA #IMPLIED
	IndexerConfig CDATA #IMPLIED
	RecordBreakerConfig CDATA #IMPLIED
	Uuid CDATA #IMPLIED
	XsltCode CDATA #IMPLIED
	XmlValidation (0|1|yes|no|true|false) "false"
	IsIndexed (0|1|yes|no|true|false) "false"
	>

<!ELEMENT GetDoc EMPTY>
<!ATTLIST GetDoc
	DocNum CDATA #IMPLIED
	>

<!ELEMENT DelDoc EMPTY>
<!ATTLIST DelDoc
	DocNum CDATA #REQUIRED
	>

<!ELEMENT AddField (#PCDATA)>
<!ATTLIST AddField
	Type CDATA #IMPLIED
	Order CDATA #IMPLIED
	FieldId CDATA #IMPLIED
	>

<!ELEMENT SetField (#PCDATA)>
<!ATTLIST SetField
	Type CDATA #IMPLIED
	Order CDATA #IMPLIED
	FieldId CDATA #IMPLIED
	>

<!ELEMENT GetField EMPTY>
<!ATTLIST GetField
	Type CDATA #IMPLIED
	Order CDATA #IMPLIED
	FieldId CDATA #IMPLIED
	>

<!ELEMENT DelField EMPTY>
<!ATTLIST DelField
	Type CDATA #IMPLIED
	FieldId CDATA #IMPLIED
	>

<!ELEMENT IndexDoc (#PCDATA)>
<!ATTLIST IndexDoc
	DocNum CDATA #REQUIRED
	>

<!ELEMENT DelDocIndex EMPTY>
<!ATTLIST DelDocIndex
	DocNum CDATA #REQUIRED
	>

<!ELEMENT GetListCol EMPTY>

<!ELEMENT ListCol (Texte*)>

<!ELEMENT GetListDoc EMPTY>

<!ELEMENT ListDoc (Texte*)>

<!ELEMENT GetListNdx EMPTY>

<!ELEMENT GetListField EMPTY>
<!ATTLIST GetListField
	Type CDATA #IMPLIED
	>

<!ELEMENT ListField (Texte*)>

<!ELEMENT ListNdx (Texte*)>

<!ELEMENT StartIndex EMPTY>

<!ELEMENT UpdateIndex EMPTY>

<!ELEMENT MakeTabmat EMPTY>

<!ELEMENT Error EMPTY>

<!ELEMENT GetStatus EMPTY>

<!ELEMENT Para EMPTY>

<!ELEMENT Phrase EMPTY>

<!ELEMENT Grec EMPTY>

<!ELEMENT Index EMPTY>

<!ELEMENT Liste EMPTY>

<!ELEMENT Article EMPTY>

<!ELEMENT MotFreq EMPTY>

<!ELEMENT FreqCroi EMPTY>

<!ELEMENT FreqDecr EMPTY>

<!ELEMENT FinMot EMPTY>

<!ELEMENT FormatXml EMPTY>

<!ELEMENT FormatHtml EMPTY>

<!ELEMENT Path (DbHome)*>

<!ELEMENT Tabmat EMPTY>

<!ELEMENT Anno EMPTY>

<!ELEMENT Signet EMPTY>

<!ELEMENT Facsim (#PCDATA)>

<!ELEMENT Link (#PCDATA)>

<!ELEMENT Base64 (#PCDATA)>

<!ELEMENT Export EMPTY>

<!ELEMENT Contexte EMPTY>

<!ELEMENT Def EMPTY>

<!ELEMENT Enabled EMPTY>

<!ELEMENT Checked EMPTY>

<!ELEMENT NewSearch EMPTY>

=== marsender/atoll-digital-library/data_unittest/xmlexec_req_01.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE atoll-plugin-xmlexec PUBLIC "-//ATOLL-DIGITAL-LIBRARY//DTD Atoll Plugin XmlExec XML V1.1//EN"
	"http://www.atoll-digital-library.org/public/atoll/dtd/atoll_plugin_xmlexec.dtd" [
	<!ENTITY reqinit SYSTEM "xmlexec_req_include.xml">
]>

<atoll-plugin-xmlexec version="1.0">
	<ReqAll>

		<!-- Init parameters -->
		&reqinit;

		<!-- Database request -->
		<ReqDb>
			<!-- Add a collection -->
			<AddCol ColId="ColDbTest" ColTitle="Test collection title" ColSalt="Test collection salt">Test collection description</AddCol>
		</ReqDb>

		<!-- Collection request -->
		<ReqCol>
			<!-- Add documents to the collection -->
			<AddDoc DocNum="0"
				FileName="/opt/atoll/data_src/demo/col01/Guy_de_Maupassant__Au_soleil.xhtml"
				DcMetadata="/opt/atoll/data_src/demo/col01/Guy_de_Maupassant__Au_soleil_dcmetadata.xml"
				IndexerConfig="/opt/dev/atoll/config/atoll_indexer_config_epub.xml"
				RecordBreakerConfig="/opt/dev/atoll/config/atoll_recordbreaker_config_epub.xml"
				Uuid=""
				XsltCode=""
				XmlValidation="0">Guy de Maupassant: Au soleil</AddDoc>
			<!-- Index the documents -->
			<IndexDoc DocNum="1" />
			<!-- Display the list of all index -->
			<GetListNdx/>
			<!-- Add search fields -->
			<AddField Type="search" Order="1" FieldId="metadata_title">Document title</AddField>
			<AddField Type="search" Order="2" FieldId="metadata_dc_title">Title</AddField>
			<AddField Type="search" Order="3" FieldId="metadata_dc_creator">Creator</AddField>
			<AddField Type="search" Order="4" FieldId="text">Texte</AddField>
		</ReqCol>

		<!-- Display the index content -->
		<ReqIndex>
      <IdCrit>text</IdCrit>
      <TypeIndex>
        <Index/>
      </TypeIndex>
      <TypeTri>
        <MotFreq/>
      </TypeTri>
      <Plage>
        <Min>0</Min>
        <Nb>20</Nb>
      </Plage>
		</ReqIndex>

		<ReqDoc>
			<DocPagPos>1-1-0</DocPagPos>
		</ReqDoc>

		<!-- Run a search -->
		<ReqSearch>
			<SearchCrit>
				<Crit>
					<IdCrit>text</IdCrit>
					<Texte><![CDATA[fÃ©erie]]></Texte>
				</Crit>
				<Crit>
					<IdCrit>metadata_dc_title</IdCrit>
					<Texte><![CDATA[<Au soleil>]]></Texte>
				</Crit>
				<Crit>
					<IdCrit>metadata_dc_creator</IdCrit>
					<Texte><![CDATA[<Guy de Maupassant>]]></Texte>
				</Crit>
			</SearchCrit>
			<NewSearch/>
			<Plage>
				<Min>0</Min>
				<Nb>100</Nb>
			</Plage>
			<TypeRes>
				<Pos><NbMot>6-6</NbMot></Pos>
			</TypeRes>
		</ReqSearch>

		<!-- Database request -->
		<ReqDb>
			<!-- Remove the collection -->
			<DelCol ColId="ColDbTest" />
			<!-- Display the list of all collections -->
			<GetListCol/>
		</ReqDb>

		</ReqAll>
</atoll-plugin-xmlexec>

=== marsender/atoll-digital-library/data_unittest/xmlexec_req_02.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE atoll-plugin-xmlexec PUBLIC "-//ATOLL-DIGITAL-LIBRARY//DTD Atoll Plugin XmlExec XML V1.1//EN"
	"http://www.atoll-digital-library.org/public/atoll/dtd/atoll_plugin_xmlexec.dtd" [
	<!ENTITY reqinit SYSTEM "xmlexec_req_include.xml">
]>

<atoll-plugin-xmlexec version="1.0">
	<ReqAll>

		<!-- Init parameters -->
		&reqinit;

		<!-- Database request -->
		<ReqDb>
			<!-- Add a collection -->
			<AddCol ColId="ColDbTest" ColTitle="Test collection title" ColSalt="Test collection salt">Test collection description</AddCol>
		</ReqDb>

		<!-- Collection request -->
		<ReqCol>
			<!-- Add documents to the collection -->
			<AddDoc DocNum="0"
				FileName="./data_unittest/docbook_xsl_test.xml"
				IndexerConfig="./data_unittest/indexer_config_test.xml"
				RecordBreakerConfig="./data_unittest/recordbreaker_config_test.xml"
				KeyWords="Test, Document"
				XsltCode="docbook-xsl-ns"
				XmlValidation="false">Document DocBook xsl test</AddDoc>
			<!-- Index the documents -->
			<IndexDoc DocNum="1" />
			<!-- Display the list of all index -->
			<GetListNdx/>
			<!-- Add search fields -->
			<AddField Type="search" Order="1" FieldId="metadata_title">Document title</AddField>
			<AddField Type="search" Order="2" FieldId="text">Text</AddField>
			<AddField Type="search" Order="3" FieldId="aut">Author</AddField>
			<AddField Type="search" Order="4" FieldId="tit">Title</AddField>
			<!-- Display the list of all search fields -->
			<GetListField Type="search" />
		</ReqCol>

		<!-- Execute a search request -->
    <ReqSearch>
      <SearchCrit>
        <Crit>
          <IdCrit>metadata_title</IdCrit>
          <Texte><![CDATA[Document DocBook xsl test]]></Texte>
        </Crit>
        <Crit>
          <IdCrit>aut</IdCrit>
          <Texte><![CDATA[VincÃ©]]></Texte>
        </Crit>
        <Crit>
          <IdCrit>aut</IdCrit>
          <Texte><![CDATA["Claudio Galderisi"]]></Texte>
        </Crit>
        <Crit>
          <IdCrit>tit</IdCrit>
          <Texte><![CDATA[premier]]></Texte>
        </Crit>
      </SearchCrit>
      <NewSearch/>
      <Plage>
        <Min>0</Min>
        <Nb>10</Nb>
      </Plage>
      <TypeRes>
        <Pos><NbMot>6-6</NbMot></Pos>
      </TypeRes>
    </ReqSearch>

		<!-- Execute a search request with a search id -->
		<!--
    <ReqSearch>
      <SearchId>084f39e7303aa0992e725c7c8d1210e8</SearchId>
      <Plage>
        <Min>0</Min>
        <Nb>10</Nb>
      </Plage>
      <TypeRes>
        <Pos><NbMot>6-6</NbMot></Pos>
      </TypeRes>
    </ReqSearch>
    -->

		<!-- Display the index content -->
		<ReqIndex>
      <IdCrit>aut</IdCrit>
      <TypeIndex>
        <Index/>
      </TypeIndex>
      <TypeTri>
        <MotFreq/>
      </TypeTri>
      <Plage>
				<!-- <Min>0</Min> or <Mot>gal</Mot> -->
				<Min>0</Min>
        <Nb>10</Nb>
      </Plage>
		</ReqIndex>

		<ReqDoc>
			<DocPagPos>1-0-5</DocPagPos>
		</ReqDoc>

		<!-- Database request -->
		<ReqDb>
			<!-- Remove the collection -->
			<DelCol ColId="ColDbTest" />
			<!-- Display the list of all collections -->
			<GetListCol/>
		</ReqDb>

		</ReqAll>
</atoll-plugin-xmlexec>

=== marsender/atoll-digital-library/data_unittest/xmlexec_test.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE atoll-plugin-xmlexec SYSTEM "../dtd/atoll_plugin_xmlexec.dtd">

<atoll-plugin-xmlexec version="1.0">
  <ReqAll>

		<!-- Init parameters -->
		<ReqInit>
			<OutFile>./data_unittest/xmlexec_res.xml</OutFile>
			<DbHome>./data_unittest/</DbHome>
			<!-- Collection name must not be the same as the unit test suite collection -->
      <Col ColId="ColUnitTest" />
      <User>mars</User>
		</ReqInit>

		<!-- Display infos about the config -->
		<ReqInfo>
			<LogFile/>
			<OutFile/>
			<Col/>
			<DbHome/>
			<User/>
			<Version/>
		</ReqInfo>

		<!-- Database request -->
		<ReqDb>
			<!-- Display the list of all collections -->
			<GetListCol/>
			<!-- Add a collection -->
			<AddCol ColId="ColUnitTest" ColTitle="Title" ColSalt="Salt">This collection is &lt;only&gt; for unit tests</AddCol>
			<!-- Set collection metadata -->
			<SetCol ColId="ColUnitTest" ColTitle="UnitTest collection title" ColSalt="UnitTest collection salt">This collection is &lt;only&gt; for unit tests set (éèà)</SetCol>
			<!-- Get collection metadata -->
			<GetCol ColId="ColUnitTest" />
			<!-- Display the list of all collections -->
			<GetListCol/>
		</ReqDb>

		<!-- Collection request -->
		<ReqCol>
			<!-- Display the list of all documents -->
			<GetListDoc/>
			<!-- Display the list of all index -->
			<GetListNdx/>
			<!-- Add documents to the collection -->
			<AddDoc FileName="./data_unittest/docbook_4-4.xml"
				IndexerConfig="./data_unittest/indexer_config_test.xml"
				RecordBreakerConfig="./data_unittest/recordbreaker_config_test.xml"
				Uuid=""
				XsltCode="docbook-xsl"
				XmlValidation="false"><![CDATA[Document DocBook 4.4]]></AddDoc>
			<AddDoc FileName="./data_unittest/docbook_5.xml"
				IndexerConfig="./data_unittest/indexer_config_test.xml"
				RecordBreakerConfig="./data_unittest/recordbreaker_config_test.xml"
				Uuid=""
				XsltCode="docbook-xsl-ns"
				XmlValidation="false"><![CDATA[Document DocBook 5]]></AddDoc>
			<!-- Set document metadata -->
			<SetDoc DocNum="1" FileName="./data_unittest/docbook_4-5.xml"
				IndexerConfig="./data_unittest/indexer_config_test.xml"
				RecordBreakerConfig="./data_unittest/recordbreaker_config_test.xml"
				Uuid=""
				XsltCode=""
				XmlValidation="false"><![CDATA[Document DocBook 4.5]]></SetDoc>
			<!-- Get document metadata -->
			<GetDoc DocNum="1" />
			<!-- Display the list of all documents -->
			<GetListDoc/>
			<!-- Index the documents -->
			<IndexDoc DocNum="1" />
			<IndexDoc DocNum="2" />
			<!-- Display the list of all index -->
			<GetListNdx/>
			<!-- Add search fields -->
			<AddField Type="search" Order="9" FieldId="text">Text</AddField>
			<AddField Type="search" Order="2" FieldId="aut">Author</AddField>
			<AddField Type="search" Order="3" FieldId="chap">Chapter</AddField>
			<AddField Type="search" Order="4" FieldId="tit">Title</AddField>
			<!-- Set search fields -->
			<SetField Type="search" Order="1" FieldId="text">Full text</SetField>
			<!-- Get search field metadata -->
			<GetField Type="search" FieldId="text" />
			<!-- Remove a search field -->
			<DelField Type="search" FieldId="tit" />
			<!-- Display the list of all search fields -->
			<GetListField Type="search" />
		</ReqCol>

		<!-- Display the index content -->
		<ReqIndex>
      <IdCrit>aut</IdCrit>
      <TypeIndex>
        <Index/>
      </TypeIndex>
      <TypeTri>
        <MotFreq/>
      </TypeTri>
      <Plage>
        <Min>0</Min>
        <Nb>20</Nb>
      </Plage>
		</ReqIndex>

		<!-- Execute a search request -->
    <ReqSearch>
      <SearchCrit>
        <Crit>
          <IdCrit>chap</IdCrit>
          <Texte><![CDATA[paragraph]]></Texte>
        </Crit>
        <Crit>
          <IdCrit>tit</IdCrit>
          <Texte><![CDATA[5e]]></Texte>
        </Crit>
        <Crit>
          <IdCrit>aut</IdCrit>
          <Texte><![CDATA[spices]]></Texte>
        </Crit>
      </SearchCrit>
      <NewSearch/>
      <Plage>
        <Min>0</Min>
        <Nb>25</Nb>
      </Plage>
      <TypeRes>
        <Pos><NbMot>6-6</NbMot></Pos>
      </TypeRes>
    </ReqSearch>

    <ReqDoc>
			<!-- Display document pages: 1-0-0 2-1-19 -->
      <DocPagPos>1-0-0</DocPagPos>
    </ReqDoc>

		<!-- Collection request -->
		<ReqCol>
			<!-- Remove the document -->
			<DelDoc DocNum="1" />
			<!-- Display the list of all documents -->
			<GetListDoc/>
			<!-- Remove the document index -->
			<DelDocIndex DocNum="2" />
			<!-- Display the list of all index -->
			<GetListNdx/>
		</ReqCol>

		<!-- Database request -->
		<ReqDb>
			<!-- Remove the collection -->
			<DelCol ColId="ColUnitTest" />
			<!-- Display the list of all collections -->
			<GetListCol/>
		</ReqDb>

  </ReqAll>
</atoll-plugin-xmlexec>

=== marsender/atoll-digital-library/data_unittest/xmlexec_req_03.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE atoll-plugin-xmlexec PUBLIC "-//ATOLL-DIGITAL-LIBRARY//DTD Atoll Plugin XmlExec XML V1.1//EN"
	"http://www.atoll-digital-library.org/public/atoll/dtd/atoll_plugin_xmlexec.dtd" [
	<!ENTITY reqinit SYSTEM "xmlexec_req_include.xml">
]>

<atoll-plugin-xmlexec version="1.0">
	<ReqAll>

		<!-- Init parameters -->
		&reqinit;

		<!-- Database request -->
		<ReqDb>
			<!-- Add a collection -->
			<AddCol ColId="ColDbTest" ColTitle="Test collection title" ColSalt="Test collection salt">Test collection description</AddCol>
		</ReqDb>

		<!-- Collection request -->
		<ReqCol>
			<!-- Add documents to the collection -->
			<AddDoc DocNum="0"
				FileName="/opt/atoll/data_src/demo/col01/VernesJulesLesNaufragesDuJonathan.html"
				IndexerConfig="/opt/dev/atoll/config/atoll_indexer_config_html.xml"
				RecordBreakerConfig="/opt/dev/atoll/config/atoll_recordbreaker_config_html.xml"
				Uuid=""
				XsltCode=""
				XmlValidation="0">Vernes, Jules - Les naufragés du Jonathan</AddDoc>
			<AddDoc DocNum="0"
				FileName="/opt/atoll/data_src/demo/col02/distributedeb.xml"
				IndexerConfig="/opt/dev/atoll/config/atoll_indexer_config_docbook.xml"
				RecordBreakerConfig="/opt/dev/atoll/config/atoll_recordbreaker_config_docbook.xml"
				Uuid=""
				XsltCode="docbook-xsl"
				XmlValidation="1">Docbook 4: How to distribute software in Debian format</AddDoc>
			<AddDoc DocNum="0"
				FileName="/opt/atoll/data_src/demo/col01/docbook_5.xml"
				IndexerConfig="/opt/dev/atoll/config/atoll_indexer_config_docbook.xml"
				RecordBreakerConfig="/opt/dev/atoll/config/atoll_recordbreaker_config_docbook.xml"
				Uuid=""
				XsltCode="docbook-xsl-ns"
				XmlValidation="1">Docbook 5</AddDoc>
			<AddDoc DocNum="0"
				FileName="/opt/atoll/data_src/demo/col01/PrechacJeanLaDuchesseDeMilan.xml"
				IndexerConfig="/opt/dev/atoll/config/atoll_indexer_config_tei.xml"
				RecordBreakerConfig="/opt/dev/atoll/config/atoll_recordbreaker_config_tei.xml"
				Uuid=""
				XsltCode="tei-xsl"
				XmlValidation="1">Préchac, Jean - La Duchesse de Milan</AddDoc>
			<!-- Index the documents -->
			<IndexDoc DocNum="1" />
			<IndexDoc DocNum="2" />
			<IndexDoc DocNum="3" />
			<!-- Display the list of all index -->
			<GetListNdx/>
			<!-- Add search fields -->
			<AddField Type="search" Order="1" FieldId="text">Texte</AddField>
			<AddField Type="search" Order="2" FieldId="aut">Author</AddField>
		</ReqCol>

		<!-- Display the index content -->
		<ReqIndex>
      <IdCrit>text</IdCrit>
      <TypeIndex>
        <Index/>
      </TypeIndex>
      <TypeTri>
        <MotFreq/>
      </TypeTri>
      <Plage>
        <Min>0</Min>
        <Nb>20</Nb>
      </Plage>
		</ReqIndex>

		<ReqDoc>
			<DocPagPos>1-1-0</DocPagPos>
		</ReqDoc>

		<!-- Database request -->
		<ReqDb>
			<!-- Remove the collection -->
			<DelCol ColId="ColDbTest" />
			<!-- Display the list of all collections -->
			<GetListCol/>
		</ReqDb>

		</ReqAll>
</atoll-plugin-xmlexec>
