=== marsender/atoll-digital-library/dtd/atoll_recordbreaker_config.dtd
<!--
	atoll_recordbreaker_config.dtd
	// 09/08/08 Version 1.0 Start implementation
-->

<!ELEMENT atoll-recordbreaker-config (action|constant)*>

<!ELEMENT action (param)*>
<!ATTLIST action
	type (add_config_param) #REQUIRED
>

<!ELEMENT param EMPTY>
<!ATTLIST param
	elem NMTOKEN #IMPLIED
	attr NMTOKEN #IMPLIED
	value NMTOKEN #IMPLIED
	type (open|close|store) "open"
>

<!ELEMENT constant (#PCDATA)>
<!ATTLIST constant
	name NMTOKEN #REQUIRED
	value NMTOKEN #REQUIRED    
>

=== marsender/atoll-digital-library/data_unittest/recordbreaker_config_test.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE atoll-recordbreaker-config PUBLIC "-//ATOLL-DIGITAL-LIBRARY//DTD Atoll RecordBreaker Config XML V1.1//EN"
	"http://www.atoll-digital-library.org/public/atoll/dtd/atoll_recordbreaker_config.dtd">

<atoll-recordbreaker-config>
  <constant name="recordbreaker_mode" value="all"/>
  <!-- Action
    	type (add_config_param) #REQUIRED
    -->
  <action type="add_config_param">
    <!-- Param
      elem NMTOKEN #IMPLIED
      attr NMTOKEN #IMPLIED
      type (open|close|store) "open"
	    <param elem="pge" type="open" />
	    -->
    <param elem="pg" type="open"/>
    <param attr="recordbreaker" type="open"/>
    <param elem="section" type="open"/>
    <param elem="head" type="close"/>
    <param elem="info" type="close"/>
    <param elem="title" type="store"/>
    <param attr="breaker" value="page" type="open"/>
    <param attr="pg" type="open"/>
    <param elem="div" type="open"/>
  </action>
</atoll-recordbreaker-config>
